### ISSUE TITLE
How can I import a vue file?

### ISSUE THREAD

**Issue by UedaTakeyuki** [crcong/vite-plugin-externals#28]
With following simple **App.vue** file:

```
<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <HelloWorld msg="Vite + Vue" />
</template>
```

Vite internal server issue error as follows:

```
Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
10:06:42 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
  Plugin: vite:import-analysis
  File: /Volumes/devtmp/MyVue3/trial/src/App.vue:3:10
  1  |  <script setup>
  2  |  import HelloWorld from './components/HelloWorld.vue'
  3  |  </script>
     |           ^
  4  |  
  5  |  <template>
      at formatError (file:///Volumes/devtmp/MyVue3/trial/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
      at TransformContext.error (file:///Volumes/devtmp/MyVue3/trial/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
      at TransformContext.transform (file:///Volumes/devtmp/MyVue3/trial/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39475:22)
      at async Object.transform (file:///Volumes/devtmp/MyVue3/trial/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
      at async loadAndTransform (file:///Volumes/devtmp/MyVue3/trial/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)
```

How have I should transformed the ``import`` of other vue component? Thank you for your help.

**Comment by UedaTakeyuki** [comment]
A reproducing environment is available at https://github.com/UedaTakeyuki/repro01. Thx.

**Comment by crcong** [comment]
You should use `@vitejs/plugin-vue` parse vue file first. Then use this plugin to external what you want.
